### ISSUE TITLE
timer_stop - Not an editor command

### ISSUE THREAD

**Issue by maxdevjs** [ruanyl/coverage.vim#3]
Hello,

I get this error on NVIM 0.2.0-dev (Build type: RelWithDebInfo) which must have [timers](https://github.com/neovim/neovim/releases/tag/v0.1.5) implemented:

```
Error detected while processing function coverage#start:
line    2:
E492: Not an editor command:     timer_stop(s:timer)
```

Some hint?

**Comment by ruanyl** [comment]
Hi, I tried with 
```
NVIM v0.2.0-96-g29e6515
Build type: Dev
```

It works fine for me. `neovim` should have `timers` since `0.1.5`. I can find the doc by: `:h timer_stop`

**Comment by maxdevjs** [comment]
Thank you for your reply.

Indeed... tried on:

```
Ubuntu 16.04.1 LTS x86_64
zsh 5.1.1, bash version 4.3.46(1)-release
NVIM 0.2.0-dev (Build type: RelWithDebInfo)
coverage.vim installed today
```

and

```
Arch x86_64
zsh 5.2, bash version 4.4.5(1)-release
NVIM 0.1.7 (Build type: RelWithDebInfo)
coverage.vim installed today
```

with the same result (E492: Not an editor command:     timer_stop(s:timer))

I tried another plugin which uses timers and works. There are dependencies that I am not aware of?

**Comment by ruanyl** [comment]
@max-devjs Can you try: `:h timer_stop ` and see if there is such function?

**Comment by maxdevjs** [comment]
Sorry, I did not specified before: yes, and it is there. Do you have, or know about, a working minimal plugin boilerplate using timer_stop / timers that I can test against?

**Comment by ruanyl** [comment]
Hi @max-devjs, can you try to update the plugin, I did a small fix which may related to the issue.

**Comment by maxdevjs** [comment]
Absolutely! I updated and  quickly tested the plugin (just to see if it works) and now I do not get anymore the error!

```
call forever!
```

Thank you very much.

P.S.: I am still curious, is this something related to nvim? The plugin was working before, even without "call", right?

**Comment by ruanyl** [comment]
Hi, I tried with `nvim` and `vim8`, they both work fine for me. Since I use Mac, I am not sure what's the reason exactly of yours.
