### ISSUE TITLE
Putting icon on uncovered lines

### ISSUE THREAD

**Issue by agarrharr** [ruanyl/coverage.vim#4]
For some reason, it is putting the icon next to any new lines I add, even if they aren't covered. I'm putting brand new functions in a file and never calling those functions. After `jest --coverage` runs, the plugin puts a green icon next to the lines in that function.

I also checked out that file and the `s` key for that file said 0.

```
"/file/path.js": {
  "path": "/file/path.js",
  "statementMap": {
    ...
    "203":{"start":{"line":389,"column":14},"end":{"line":389,"column":15}}
    ...
  }
}
```

```
"s": {
  ...
  "203":0,
  ...
}
```

**Comment by ruanyl** [comment]
@aharris88 Thanks for reporting. Seems there is a bug in computing the covered lines from statement map. I will look into this weekend. Pull requests are welcome :)

**Comment by agarrharr** [comment]
I'm guessing the bug has to be [here](https://github.com/ruanyl/coverage.vim/blob/5f52b5b84a4d916888d7907cda0242de18c1085f/autoload/coverage.vim#L62-L77), but I'm not sure what the problem is. It looks good to me.

**Comment by ruanyl** [comment]
Yes, that's right. I am working on it, should be fixed soon.

**Comment by ruanyl** [comment]
@aharris88 The issue should be fixed now.

ref:
How covered/uncovered lines are computed.

https://github.com/istanbuljs/istanbul-lib-coverage/blob/22e154c9c2040101351f7f0147d29629149cc183/lib/file.js#L163

https://github.com/gotwarlost/istanbul/blob/master/lib/object-utils.js#L51

**Comment by agarrharr** [comment]
That works. Thanks! 👍
